# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQrQugq-Go3ZkoNLdqoSYvuAU5srWDIz
"""

from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
X = iris.data
Y = iris.target

df = pd.DataFrame(X, columns = iris.feature_names)
df['species'] = Y
print(df.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42, stratify=Y
)

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(max_iter=200)
clf.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report

y_pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=iris.target_names))

from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(random_state=42)
tree.fit(X_train, y_train)
print("Decision Tree Accuracy:", tree.score(X_test, y_test))

import matplotlib.pyplot as plt
import seaborn as sns

sns.scatterplot(
    x=df['petal length (cm)'],
    y=df['petal width (cm)'],
    hue=df['species'],
    palette="deep"
)
plt.title("Iris species distribution (petal length vs width)")
plt.show()

sns.scatterplot(
    x=df['sepal length (cm)'],
    y=df['sepal width (cm)'],
    hue=df['species'],
    palette="deep"
)
plt.title("Iris species distribution (sepal length vs. width)")
plt.show()

